version: '3.8'
services:
  lightpanda:
    image: ghcr.io/lightpanda-io/browser:latest
    ports:
      - "9222:9222"
    command: 
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --headless
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
    environment:
      - DISPLAY=:99
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9222/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
