// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lasdcxnkoptubfoaqinw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhc2RjeG5rb3B0dWJmb2FxaW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjI4MzIsImV4cCI6MjA3NDUzODgzMn0.6F_qrS1a-U9bZQoRMAPuTOJUK3bnLYubezW4ldZ4-M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});